PIN_ROOT ?= /home/viken/pin-3.13-98189-g60a6ef199-gcc-linux

CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
